import localFont from "next/font/local";
import "./globals.css";
import linksIcon from "./images/icon-links-header.svg"
import previewHeader from "./images/icon-profile-details-header.svg"
import navIcon from "./images/logo-devlinks-large.svg"
import Image from 'next/image';
import Link from 'next/link';
const InstrumentSansBold = localFont({
  src: "./fonts/static/InstrumentSans-Bold.ttf",
  variable: "--font-instrument-sans-bold",
});
const InstrumentSansRegular = localFont({
  src: "./fonts/static/InstrumentSans-Regular.ttf",
  variable: "--font-instrument-sans-regular",
});
const InstrumentSansSemiSemibold = localFont({
  src: "./fonts/static/InstrumentSans-Semibold.ttf",
  variable: "--font-instrument-sans-semibold",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* MADE BY ADITYA 2K22/SE/009 DTU */}
      <body
        className={`${InstrumentSansBold.variable} ${InstrumentSansRegular.variable} ${InstrumentSansSemiSemibold} antialiased`}
      >
        <header className="text-gray-600 body-font border-[16px] border-gray-50">
          <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
              <Image alt="abc" src={navIcon} priority/>
            </a>
            <nav className="md:ml-auto md:mr-auto flex flex-wrap space-x-8 items-center text-base justify-center">
              <div className="flex flex-row bg-purple-100 items-center p-2 m-1 border rounded-md text-purple-900 instrument-sans-semibold"><Image alt="" src={linksIcon}/><Link href="/gen" className="mr-1 ml-1 hover:text-purple-600">Links </Link></div>
              <div className="flex flex-row bg-purple-100 items-center p-2 m-1 border rounded-md text-purple-900 instrument-sans-semibold"><Image alt="" src={previewHeader}/><Link href="/profile-details" className="mr-1 ml-1 hover:text-purple-600">Profile Details</Link></div>
            </nav>
            <button className="bg-transparent hover:bg-purple-400 text-purple-800 font-semibold hover:text-white py-2 px-4 border border-purple-500 hover:border-transparent rounded instrument-sans-regular">
              Preview
            </button>
          </div>
        </header>
      {children}
      </body>
    </html>
  );
}